name: Testing Bach

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Test Bach Testing Framework
      run: ./run-tests.sh

  test-on-windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
    - name: Ensure a specific version of Git
      run: choco install -y --accept-license git --version 2.24.0 --force
      shell: pwsh
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Test Bach Testing Framework
      run: |
        & $Env:ProgramFiles\\Git\\bin\\bash.exe -c './run-tests.sh'
      shell: pwsh
